[workspace]
resolver = "2"
members = [
    "nenya",
    "nenya-sentinel",
]

[workspace.package]
edition = "2021"
authors = ["Matthew Emerson <emersonmde@protonmail.com>"]
license = "MIT"
repository = "https://github.com/emersonmde/nenya"
readme = "README.md"
